apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webs
  name: webs
spec:
  replicas: {{ .Values.replicaCount   }}
  selector:
    matchLabels:
      app: webs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webs
    spec:
      containers:
      - image: vimal13/apache-webserver-php:v1
        name: apache-webserver-php
        resources: {}
status: {}
